# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f71d935e3a2e3012951b0dcab504a2936b685ecf790e01336a1b61f4a27d04fbbd7c4e3d4c5db6863acc5c984c8a6301e39b274d28800ce7d63d54673ffafb

test:
  secret_key_base: 49fe2256933f9ad6f11b2973d25b77b7e1176d04972241b16f97e2be82ff7d0682d2b20fa6ef811e5d78a8b62bba10f6d5d4a7504181a3d844870db487df49b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
